name: Build Multi-arch Image

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        ARCH: [linux/ppc64le, linux/amd64]
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#       - name: Login to container registry
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_TOKEN }}

#       - name: Build and Push Image
#         uses: docker/build-push-action@v3
#         with:
#           tags: quay.io/siddhesh_ghadi/multi-arch-gha:latest
#           platforms: linux/amd64,linux/ppc64le
#           push: true

      - name: Build and Push image
        run: |
          
          if [[ "$ARCH" == "linux/ppc64le" ]]; then
            TAG=ppc64le
          else
            TAG=amd64
          fi
          
          docker buildx build --platform ${ARCH} --tag mha:${TAG} --load -f Dockerfile .. 
          docker image ls
