name: Build Multi-arch Image

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
          ARCH: [linux/ppc64le, linux/amd64]
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 

#       - name: Build and Push Image
#         uses: docker/build-push-action@v3
#         with:
#           tags: multi-arch-gha:latest
#           platforms: linux/amd64,linux/ppc64le
#           push: false

      - name: Build and Push image
        run: |
        
          echo ${{ matrix.ARCH }}

          if [[ "${{ matrix.ARCH }}" == "linux/ppc64le" ]]; then
            export TAG=ppc64le
          else
            export TAG=amd64
          fi

          echo "Building for $TAG"

          docker buildx build --platform ${{ matrix.ARCH }} --tag multi-arch-gha:latest-${TAG} -f Dockerfile ..
          docker image ls
          docker inspect multi-arch-gha:latest-${TAG} | grep Arch
          

#       - name: Build image
#         run: |
#           docker buildx build --load --platform ${{ matrix.ARCH }} -t multi-arch-gha:${TAG} .
#           docker image ls
#           docker inspect multi-arch-gha:latest | grep Arch

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: multi-arch-gha:latest-$TAG}
          path: /tmp/multi-arch-gha-${TAG}
          
  multi-arch-manifest:
    needs: build
    name: Create manifest
    runs-on: ubuntu-latest
    steps:
      - name: Download PPC Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: multi-arch-gha:latest-ppc64le
          path: /tmp/multi-arch-gha-ppc64le
          
      - name: Download AMD Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: multi-arch-gha:latest-amd64
          path: /tmp/multi-arch-gha-amd64
      
      - name: Load image into docker daemon
        run: |
          docker load --input /tmp/multi-arch-gha-ppc64le
          docker load --input /tmp/multi-arch-gha-amd64
          docker image ls -a
          
      - name: Create manifest
        run: |
          docker manifest create multi-arch-gha-ppc64le multi-arch-gha-amd64 multi-arch-gha:latest
          
    
      
